---
services:
    - id: inbox
      type: inbox
      address: /services/inbox
      description: Inbox Service
      destination_collection_required: yes
      accept_all_content: no
      authentication_required: yes
      supported_content:
        - urn:stix.mitre.org:xml:1.1.1
        - urn:stix.mitre.org:xml:1.2
      protocol_bindings:
        - urn:taxii.mitre.org:protocol:http:1.0
        - urn:taxii.mitre.org:protocol:https:1.0

    - id: discovery
      type: discovery
      address: /services/discovery
      description: Discovery Service
      advertised_services:
        - inbox
        - discovery
        - collection_management
        - poll
      protocol_bindings:
        - urn:taxii.mitre.org:protocol:http:1.0
        - urn:taxii.mitre.org:protocol:https:1.0

    - id: collection_management
      type: collection_management
      address: /services/collection-management
      description: Collection Management Service
      protocol_bindings:
        - urn:taxii.mitre.org:protocol:http:1.0
        - urn:taxii.mitre.org:protocol:https:1.0

    - id: poll
      type: poll
      address: /services/poll
      description: Poll Service
      subscription_required: no
      max_result_count: 100
      max_result_size: 10
      authentication_required: yes
      protocol_bindings:
        - urn:taxii.mitre.org:protocol:http:1.0
        - urn:taxii.mitre.org:protocol:https:1.0

collections:
  - name: my_collection
    available: true
    accept_all_content: true
    type: DATA_SET

    service_ids:
      - inbox
      - collection_management
      - poll

accounts:
  - username: guest
    password: guest
    permissions:
      my_collection: read
  - username: admin
    password: admin
    is_admin: yes
